### ISSUE TITLE
An option to inherit stdout for installation output

### ISSUE THREAD

**Issue by zkochan** [zkat/npx#121]
I am adding npx to pnpm. It all works fine but the installation logs are not printed. However, when it is used with npm, a progress bar is shown (although w/o colors).

By looking into the code, it seems like the stdout is piped, concatenated and returned as a single string value (https://github.com/zkat/npx/blob/latest/child.js#L49).

Setting stdout to 'inherit' [here](https://github.com/zkat/npx/blob/latest/index.js#L238) prints pnpm's output nicely.

Would you accept a PR that would add an option to inherit stdout for installation output?

**Comment by zkat** [comment]
The progress bar goes to `stderr`, not `stdout`, so I'm confused as to why the change you're proposing would even work. As far as *installation* goes, `stderr` is already inherited (by passing through `2` as the `stderr` target here https://github.com/zkat/npx/blob/latest/index.js#L238), so you _should_ be getting output in the terminal during installations, but only if you're using `stderr` for progress bar stuff (which I recommend, 'cause that's where that stuff tends to go).

The reason this is collecting `stdout` into a string is not to pass it through to the terminal, it's to collect the `--json` output from the install command, which is then used here: https://github.com/zkat/npx/blob/latest/index.js#L74-L77

As a general thing, I'm more than happy to accept PRs from you if it gets things working better with pnpm. Let me know if this helps and let's see if we can make the changes you need <3

**Comment by zkochan** [comment]
hm, I thought `stderr` was for printing errors.

pnpm uses only `stdout`, so that's why 'inherit' would solve the output issue.

Also, I never heard about the `--json` flag. Is it documented somewhere as I can't find it on the [npm install](https://docs.npmjs.com/cli/install) docs page.

**Comment by zkochan** [comment]
Sorry for accidentally closing the issue.

For now, my solution was to set a `installerStdio` option: https://github.com/zkochan/npx/commit/559b7f3b194c792e76c3c650eb1bd031a1a08f6e

**Comment by zkat** [comment]
npm uses stdout as its data output, which is conventional (even outside of npm) because of piping stuff: `stderr` is often used for sideline data that isn't meant to be consumed by other applications (such as logging output).

Here's the docs for the `--json` option: https://docs.npmjs.com/misc/config#json. It's more of a general option that applies to a bunch of different commands, so it's in `npm help 7 config`.

Anyway, the only reason you're getting away with that particular patch is because JSON parse failures are ignored (which is there to support installation using older npm versions). I'm fine with your `opts.installerStdio` patch, as long as it's restricted to only be available if you're using `libnpx` directly (so, I'd rather regular npx cli users not be able to pass this option in). I assume that'll provide a better user experience for you, since having users enter `$ npx --npm pnpm ....` every single time they use it would suck. Having a dedicated `$ pnpx ...` command sounds way nicer?

How's that sound?

**Comment by zkochan** [comment]
Yes, sounds great. That is exactly what I did. I called libnpx with that option from pnpm and created pnpx (https://github.com/pnpm/pnpm/commit/ee6d941e2a1912a788f3b4053f98654eacbdca53).

I'll create a PR later.

***
Edit:

I will probably implement the `--json` flag in pnpm as well.. but much later

**Comment by zkat** [comment]
SGTM! I look forward to it! :tada:
