### ISSUE TITLE
"Path must be a string. Received undefined"

### ISSUE THREAD

**Issue by UTGuy** [zkat/npx#144]
* npm  v5.51
* node v8.9.0

![image](https://user-images.githubusercontent.com/1872858/34420828-b0250742-ebd9-11e7-8cc8-a392987b43f6.png)

... it seems that anytime I run an npx command it shows "Path must be a string. Received undefined"

**Comment by only-cliches** [comment]
Also getting this error, it seems like npx isn't able to scan and find already installed packages.

- Windows 10
- npm 5.5.1
- node 8.9.3

**Comment by styfle** [comment]
I get the same error on Windows 10.

```
C:\Users\styfle>node --version
v8.9.4

C:\Users\styfle>npm --version
5.6.0

C:\Users\styfle>npx --version
npx: installed 1 in 2.147s
Path must be a string. Received undefined
9.7.1
```

**Comment by laggingreflex** [comment]
Dupe https://github.com/zkat/npx/issues/148

**Comment by denishowe** [comment]
npx.cmd does
`CALL "%NODE_EXE%" "%NPX_CLI_JS%" prefix -g`
which is
`node c:/nodejs/node_modules/npm/bin/npx-cli.js prefix -g`
when it looks like it should be doing
`npm prefix -g`
Where exactly does npx.cmd come from?

**Comment by laggingreflex** [comment]
[This PR should fix it](https://github.com/npm/npm/pull/19608)

**Comment by bluelovers** [comment]
```
The "path" argument must be of type string
```

**Comment by oshingc** [comment]
I have this issue...

**Comment by Sawtaytoes** [comment]
@laggingreflex Looks like the PR failed when run through the CI tool.

**Comment by colwilson-mo** [comment]
Windows 10

node -v
v8.9.4

npm -v
5.6.0

npx -v
npx: installed 1 in 2.458s
Path must be a string. Received undefined
9.7.1

**Comment by rmx90210** [comment]
Same issue here.

Windows 7
Node 8.9.4
npm 5.6.0
npx 9.7.1

**Comment by Darkle** [comment]
I'm getting this as well.

Windows 10
Node v8.10.0
npm 5.7.1
npx 9.7.1

**Comment by eybbus** [comment]
Same issue here.

Windows 10 64 bit
Node 8.9.4
npm 5.6.0
npx 9.7.1

**Comment by sandyarmstrong** [comment]
What version will include the fix?

**Comment by cekvenich** [comment]
Same here, I have the bug.

**Comment by cekvenich** [comment]
Solved in: https://github.com/zkat/npx/issues/168

This issue here #144 should be closed.

**Comment by IT0315** [comment]
https://github.com/webpack/webpack/issues/2463

**Comment by rich-newman** [comment]
@cekvenich I don't understand how #168 relates to this.  Can you explain please?  Are you suggesting that remapping the js file extension will fix this (I've tried remapping it to node.exe and it make no difference to this issue)?

**Comment by cekvenich** [comment]
Happy to try to help. The reason people all over www get 'Path must be a string' in Windows is because it it not running node, it is running something else.
After windows does some windows update, it breaks things.

So I found that it is not running node as expected. Normally npx does node to run your js. 
But sometimes, on windows it runs 'JScript' instead of node. 
That is easy to prove, and 168 shows how. The 'path must be a string' error does not come from node.

So now that we know what the exact problem is and we can reproduce it, it should be easier to fix.
Sadly I can't find source code for the npx.cmd.  
(also I complained that node org should be doing better testing for windows )

Does that help you @rich-newman ?

**Comment by shawwn** [comment]
I'm getting this issue on npx 9.7.1, windows 10:

![image](https://user-images.githubusercontent.com/59632/39392329-6871c67a-4a79-11e8-8a42-9c05add9ea00.png)

This is confusing for end users, since I want to rely on npx to start my program.

In general, is there a way to get npx to shut up? I'd prefer a mode that doesn't log anything at all, unless there's an error.

**Comment by TotallyInformation** [comment]
I also added the following to #168 - and I don't believe it is "fixed" by that issue. The issue remains.

---- 

Given that npx is now distributed with Node.JS, this is a VERY IMPORTANT thing to fix!

I don't pretend to understand all of the technical details but please bear in mind that this - to users - is an npx error, not an npm error. That's because npm works just fine on Windows, npx does not.

I am not trying to be negative. This is a great tool and I want to see it succeed.

**Comment by zkat** [comment]
This should have been fixed with `npm@5.8.0` (if using the bundled npx) and `npx@10` (if you're using a standalone npx install). Please don't comment unless you have this bug _with one of those versions or later_.

**Comment by rich-newman** [comment]
@zkat Both the 'recommended' LTS version of node (8.11.1) AND the 'current' version (10.0.0) seem to install npm 5.6.0 currently on Windows, and have the problem.  So are you saying we just need to wait for the node team to fix this?

**Comment by zkat** [comment]
@rich-newman pretty much. They'll eventually get around to upgrading the CLI, when they find the time.

In the meantime, though, you can do `npm i -g npx` to install the standalone version of npx, which should fix this.

**Comment by styfle** [comment]
```
npm install -g npm@5.8.0
npm install -g npx@10.0.1
```

**Comment by zkat** [comment]
I assume this is fixed since everyone still reporting it is on older versions of npx.

Just upgrade, y'all.

**Comment by shawwn** [comment]
Could we reopen this?

We want to ship npx as a solution with our product. When our product starts up, we want to use a custom version of node -- node@10. This will work if we run it with `npx`.

But npx is reporting an ugly error message, and confusing users.

Our users happen to be developers. Telling them "Upgrade your npm!" is not something they're willing to do. I'd hesitate to do it, for example, because I don't want to modify my default development environment.

Is there no other solution?

**Comment by shawwn** [comment]
Mm.. Rather than merely complain about this, I'll try looking into a way to fix it for existing users.

It seems premature to close the issue, since it seems like npx ought to be able to run without triggering any npm error messages. Relying on the latest npm isn't quite a solution, especially since Node 8 is the latest LTS.

It looks like https://github.com/npm/npm/pull/19608/files was a partial attempt at a fix. What went wrong? I can try to solve the rest.

The other request was a "quiet mode" so that npx doesn't print out anything under any circumstances unless there's an error. No installation messages, for example. Should that be submitted as a separate issue?

**Comment by shawwn** [comment]
Thanks! I'll retest on Windows to confirm.

The only other request would be a quiet mode.

**Comment by zkat** [comment]
@shawwn `-q` is there.

**Comment by shawwn** [comment]
It’d be nice for quiet to be the default, since it matches unix utility philosophy, but this gets the job done for our app:

npx -q -p node@10 .

Interestingly though, it doesn’t work when -p is omitted:

```
$ npx -q node@10 .

Error: The module 'build/Release/exokit.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

This probably isn’t the right place to ask, but is that expected behavior? `npx node@10 —version` reports v10.0.0, so intuitively `npx node@10 .` seems like it should run the current project with node 10.

**Comment by zkat** [comment]
@shawwn I suggest you `man npx` and read the documentation. It is very clear about how the `-q` option works. npx will not be silent by default because the lack of feedback causes confusion to users. I'm writing a tool that's easy to pick up, not `dd(1)`. It's also about the same amount of feedback npm itself gives (if not less), so I consider it acceptable. All that output goes to `stderr` anyway so it won't affect piping.

As far as your next problem goes, `npx node@10 .` _is_ running the current project with node 10. The problem is you've got native plugins, and simply using a different node version doesn't recompile it :) You'll need something like `npx -p node@10 -c 'npm rebuild && node .'`.

If you have further questions, you should _really_ just make a new issue. This isn't the issue to ask every single thing you're wondering about and suggest several feature requests.

**Comment by shawwn** [comment]
Sorry, you’re right of course. Lack of sleep.

Thank you.

**Comment by cekvenich** [comment]
Still the same error, no reason to close the bug:
http://dropbox.com/s/rtduyx9xq0d7whg/npx.PNG
You can see we are using latest version of npm in the screen shot.  

Regarding 'This should have been fixed ' seems a big vague, or even magical.  What is the commit | pr link that fixes this issue?

**Comment by Zer0ne83** [comment]
Also getting this error and spent the last few hours upgrading, downgrading, wiping clean, rebuilding... with vs. 6.0.0.0 and 5.80 - deffo not fixed.

**Comment by prumbles** [comment]
I am using git bash under windows 10.  I solved the issue by uninstalling node and reinstalling under the folder "c:\nodejs".  The default location it installs to is irritating, because it has a "space" in it (c:\Program files\nodejs".  That may be the issue, or it may have just been fixed with a reinstall - don't know for certain.

**Comment by FlorianGrimm** [comment]
Ola
I think I found the line that produes the error.

I found the text "Path must be a string. Received " in node.exe 

```
function assertPath(path) {
  if (typeof path !== 'string') {
    throw new TypeError('Path must be a string. Received ' + inspect(path));
  }
}

// Resolves . and .. elements in a path with directory names
function normalizeStringWin32(path, allowAboveRoot) {
```

I add logs via console.error to
C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\index.js

the modifed source

```
return ensurePackages(argv.package, argv).then(results => {
          if (results && results.added && results.updated && !argv.q) {
            console.error(Y()`npx: installed ${
              results.added.length + results.updated.length
            } in ${(Date.now() - startTime) / 1000}s`)
          }
          if (
            argv.command &&
            !existing &&
            !argv.packageRequested &&
            argv.package.length === 1
          ) {
			  console.error("results.bin", inspect(results.bin)); 
            return promisify(fs.readdir)(results.bin).then(bins => {
			  console.error(bins); 
              if (process.platform === 'win32') {
                bins = bins.filter(b => b !== 'etc' && b !== 'node_modules')
              }
              const cmd = new RegExp(`^${argv.command}(?:\\.cmd)?$`, 'i')
              const matching = bins.find(b => b.match(cmd))
				console.error("cmd", inspect( cmd)); 
				console.error("bins", inspect( bins)); 
				console.error("matching", inspect( matching)); 
				console.error("bins[matching] || bins[0]", inspect( bins[matching] || bins[0])); 
// path.resolve throws the error
				const r=path.resolve(results.bin, bins[matching] || bins[0])

				console.error("r", inspect( r )); 
                return r;
            }, err => {
              if (err.code === 'ENOENT') {
                throw new Error(Y()`command not found: ${argv.command}`)
              } else {
			    console.error(err); 
                throw err
              }
            })
          } else {
  		    console.error("existing"); 
            return existing
          }
        })
```
		
the output

```
c...>FOR /F "delims=" %F IN ('CALL "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nodejs\\node_modules\npm\bin\npx-cli.js" prefix -g') DO (SET "NPM_PREFIX_NPX_CLI_JS=%F\node_modules\npm\bin\npx-cli.js" )

npx: installed 1 in 1.875s
results.bin 'C:\\Users\\f.grimm\\AppData\\Roaming\\npm-cache\\_npx\\5844'
[ 'etc', 'node_modules' ]
cmd /^prefix(?:\.cmd)?$/i
bins []
matching undefined
bins[matching] || bins[0] undefined
ERROR
Path must be a string. Received undefined
```

**Comment by FlorianGrimm** [comment]
I'm using npx and webpack the first time, so I really don't know if this is good idea .. but it works

C:\Program Files\nodejs\node_modules\npm\node_modules\libnpx\index.js

```
if ((!existing && !argv.call) || argv.packageRequested) {
        // We only fire off the updateNotifier if we're installing things
        if (argv.npxPkg) {
          try {
            require('update-notifier')({
              pkg: require(argv.npxPkg)
            }).notify()
          } catch (e) {}
        }	
        // Some npm packages need to be installed. Let's install them!
        return ensurePackages(argv.package, argv).then(results => {
          if (results && results.added && results.updated && !argv.q) {
            console.error(Y()`npx: installed ${
              results.added.length + results.updated.length
            } in ${(Date.now() - startTime) / 1000}s`)
          }
          if (
            argv.command &&
            !existing &&
            !argv.packageRequested &&
            argv.package.length === 1
          ) {
            return promisify(fs.readdir)(results.bin).then(bins => {
              if (process.platform === 'win32') {
                bins = bins.filter(b => b !== 'etc' && b !== 'node_modules')
              }
              const cmd = new RegExp(`^${argv.command}(?:\\.cmd)?$`, 'i')
              const matching = bins.find(b => b.match(cmd))
				const binmatching = bins[matching] || bins[0];
				if (binmatching){
					return path.resolve(results.bin, binmatching)	
				} else {
					return null;
				}								
            }, err => {
              if (err.code === 'ENOENT') {
                throw new Error(Y()`command not found: ${argv.command}`)
              } else {
                throw err
              }
            })
          } else {
            return existing
          }
        })
      } else {
        // We can skip any extra installation, 'cause everything exists.
        return existing
      }
    }).then(existing => {
		if (existing){
			return execCommand(existing, argv)	
		}      
    }).catch(err => {
      !argv.q && console.error(err.message)
      process.exitCode = err.exitCode || 1
    })
  })
}
``` 

Flori

**Comment by FranklinYu** [comment]
@cekvenich It's not fixed in the NPX 9.7.1 bundled in NPM 5.8.0. It's only fixed in 10.2.0. In your case, the last command was still running NPX 9.7.1. Either update NPM or NPX to latest version to solve the issue.

**Comment by magnusriga** [comment]
I am running NPX 10.2.0 and NPM 6.0.1 on Windows 10 Pro, and I can confirm that the issue is not fixed on my system. I still get the "Path must be a string. Received undefined" error.

**Comment by Darkle** [comment]
@magnusriga What does running `where npx` in the terminal print out?

**Comment by magnusriga** [comment]
For instance: npx install-peerdeps --dev eslint-config-airbnb-base

Which ran: npm install eslint-config-airbnb-base@12.1.0 eslint@^4.9.0 eslint-plugin-import@^2.7.0 --save-dev

However, the "path must be a string" error message did not show when running the npm command directly, only when running npx.

Here is the full output:

```
npx install-peerdeps --dev eslint-config-airbnb-base
npx: installed 1 in 3.329s
**Path must be a string. Received undefined**
npx: installed 69 in 13.076s
C:\Users\userName\AppData\Roaming\npm-cache\_npx\30544\node_modules\install-peerdeps\lib\cli.js
install-peerdeps v1.7.0
Installing peerdeps for eslint-config-airbnb-base@latest.
npm install eslint-config-airbnb-base@12.1.0 eslint@^4.9.0 eslint-plugin-import@^2.7.0 --save-dev

npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\userName\somePath\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\userName\somePath\package.json'
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN responsive-boxes No description
npm WARN responsive-boxes No repository field.
npm WARN responsive-boxes No README data
npm WARN responsive-boxes No license field.

+ eslint-plugin-import@2.7.0
+ eslint-config-airbnb-base@12.1.0
+ eslint@4.9.0
added 185 packages from 159 contributors in 107.152s
[+] no known vulnerabilities found [297 packages audited]

SUCCESS eslint-config-airbnb-base
  and its peerDeps were installed successfully.
```

**Comment by marco-carvalho** [comment]
Windows 10 here:

`node -v`
v10.1.0

`npm -v`
6.1.0-next.0

`npm i -g npx`
C:\Users\mlj\AppData\Roaming\npm\npx -> C:\Users\mlj\AppData\Roaming\npm\node_modules\npx\index.js
+ npx@10.2.0
added 484 packages from 651 contributors in 154.963s

`npx -v`
npx: installed 1 in 4.5s
The "path" argument must be of type string. Received type undefined
9.7.1

---

I can't use NPX like this:

`npx eslint src`
npx: installed 1 in 4.679s
The "path" argument must be of type string. Received type undefined
C:\Users\mlj\Desktop\Git\untappd\node_modules\eslint\bin\eslint.js

**Comment by laggingreflex** [comment]
This issue will likely continue to appear (at least on Windows) until the next version of **NodeJS  itself ships with npm6** (Node10.1.0 still ships with npm5.6.0). 

This is because the `PATH` variable (on Windows) is set in such a way that it prefers `C:\Program Files\nodejs` (System) over (User) `%AppData%\npm`. So even if you upgrade npm/npx manually it only gets installed in `%AppData%/npm`. (although npm somehow manages to overcome this issue, npx doesn't and while it'll be a good feature to add in the future but it still won't solve the issue this time)

So in the mean time you can solve this by [modifying your **System** `PATH` variable][1] and put `%AppData%\npm` before `C:\Program Files\nodejs`

Or you can copy the `npx.cmd` (after upgrading to npm6) file from `%AppData%\npm\node_modules\npm\bin` (or [from the repo][2]) to `C:\Program Files\nodejs`

[19608]: https://github.com/npm/npm/pull/19608
[1]: https://stackoverflow.com/questions/24219627/how-to-update-system-path-variable-permanently-from-cmd
[2]: https://github.com/npm/npm/tree/latest/bin

**Comment by marco-carvalho** [comment]
copying the `npx.cmd` file from `%AppData%\npm\node_modules\npm\bin` to `C:\Program Files\nodejs` didn't worked here

i'm still receiving the same message:
`npx eslint src`
npx: installed 1 in 4.198s
The "path" argument must be of type string. Received type undefined
C:\Users\mlj\Desktop\Git\foursquare\node_modules\eslint\bin\eslint.js

**Comment by FranklinYu** [comment]
@marco-carvalho How about directly invoke the `npx.cmd`? Use its full path (`%AppData%\npm\node_modules\npm\bin\npx.cmd`).

**Comment by FranklinYu** [comment]
@magnusriga So what does running `where npx` in the terminal print out? @Darkle  asked that because this is *very* important. It's the first step of debugging.

**Comment by FranklinYu** [comment]
@laggingreflex I wonder how NPM worked around this `%PATH%` issue?

**Comment by TotallyInformation** [comment]
@franklinyu `where.exe` has only just been introduced to Windows 10 in the 1803 release so most people wont have it. On my system (which does have 1803), running `where npx` in PowerShell returns nothing. Running it in CMD, returns:

```
λ where npx
C:\Program Files\nodejs\npx
C:\Program Files\nodejs\npx.cmd
```

```
λ node --version && npm --version && npx --version 
v8.11.1                                            
5.6.0                                              
                                                   
                                                   
   ╭─────────────────────────────────────╮         
   │                                     │         
   │   Update available 5.6.0 → 6.1.0    │         
   │       Run npm i npm to update       │         
   │                                     │         
   ╰─────────────────────────────────────╯         
                                                   
npx: installed 1 in 4.381s                         
Path must be a string. Received undefined          
9.7.1                                              
```

It should be noted that I have the 64bit version of Node installed.

**Comment by FranklinYu** [comment]
@TotallyInformation Yes, `where` is typically used in CMD. In PowerShell it's `Get-Command` or `gcm` (optionally with the `-All` flag). @Darkle probably assumed that most user uses CMD; anyway if @magnusriga reply with anything related, we would know what shell he is in, and then help him troubleshooting.

In your specific case, https://github.com/zkat/npx/issues/144#issuecomment-391031816 applies.

**Comment by mdalikazi** [comment]
To fix this on Windows you have to add nvm path to System Variables.

System Info -> System Properties -> Environment Variables -> under System Variables -> New -> `C:\Users\%USERPROFILE%\AppData\Roaming\npm`

**Comment by FranklinYu** [comment]
@mdalikazi By

```text
C:\Users\%USERPROFILE%\AppData\Roaming\npm
```

did you mean

```text
C:\Users\%USERNAME%\AppData\Roaming\npm
```

? This *has already* been mentioned in https://github.com/zkat/npx/issues/144#issuecomment-391031816, thank you.

**Comment by magnusriga** [comment]
Hi Guys,

Thanks for input. I actually tried to change the environment variable, and it did not work.

More specifically, I changed "C:\Users\%USERNAME%\AppData\Roaming\npm" in PATH to "%AppData%\npm". Given that the two point to the same folder, no change was seen (i.e. still the same error message).

I do not have "C:\Program Files\nodejs" in PATH.

Any other thoughts?

**Comment by magnusriga** [comment]
@franklinyu @Darkle 

where npx gives me the following:

C:\Users\magnusga>where npx
C:\Program Files\nodejs\npx
C:\Program Files\nodejs\npx.cmd
C:\Users\magnusga\AppData\Roaming\npm\npx
C:\Users\magnusga\AppData\Roaming\npm\npx.cmd

So, it picks up the "Program Files" address, without it being in my path environment variable. I am not sure how to force it to use the AppData address.

**Comment by Darkle** [comment]
@magnusriga I recommend using https://www.rapidee.com/en/screenshots to edit your path, its free and works well.

Also, don't forget to restart after you make a change.

**Comment by magnusriga** [comment]
@Darkle I found "C:\Program Files\nodejs" in my system variables (as opposed to user variables).

I went ahead and deleted it, and now when running npx:

> 'node' is not recognized as an internal or external command,
> operable program or batch file.

"where npx" outputs the following, as expected:

C:\Users\magnusga\AppData\Roaming\npm\npx
C:\Users\magnusga\AppData\Roaming\npm\npx.cmd

Somehow I guess it should take node.exe from the nodejs folder, and npx from AppData?

**Comment by magnusriga** [comment]
OK, so I did something that seemed to work. Instead of **only** deleting "C:\Program Files\nodejs" from system variables ("path" variable), I also added it to user variables ("path" variable), but after "%AppData%\npm".

I now get no error messages. Hopefully it has no other undesirable side-effects.

"where npx" shows the right order:

C:\Users\magnusga\AppData\Roaming\npm\npx
C:\Users\magnusga\AppData\Roaming\npm\npx.cmd
C:\Program Files\nodejs\npx
C:\Program Files\nodejs\npx.cmd

**Comment by Darkle** [comment]
>  I also added it to user variables ("path" variable), but after "%AppData%\npm".

That should be alright. 

I usually do it the other way and add `C:\Users\coop\AppData\Roaming\npm\` above the `C:\Program Files\nodejs` path in the system variables, but doing it all in the user variables should be fine too.

Glad you got it working. 😀

**Comment by TotallyInformation** [comment]
Thanks for everyone's feedback. However, I would point out that all the excellent suggestions here are **workarounds** - they are not a solution. 

My point is that npx is integrated into Node.JS installations and so that needs to work without user intervention. Applying workarounds often results in long term support issues.

The reason for having an open issue in the npx repo (not just node/npm) is that some users will see this as a problem with npx and should therefore be able to see what the problem is and where the problem comes from.

**Comment by FranklinYu** [comment]
@TotallyInformation Then the answer is obvious: don't use `npx` until you are in a Node.js release with fixed version of NPX. Regard this as something you pay for cutting-edge technology; Node.js 8 was simply not yet ready for `npx`. I would prefer wait until Node.js 10 LTS.

Or if you know some one in Microsoft, tell them that the `%PATH%` rule is really annoying. That helps everyone, not just Node.js users. It's easy and typical for Linux user to upgrade their global NPM; that shoouldn't be an issue. I believe it's the environment variable rule in Windows that truly annoys most users.

**Comment by Darkle** [comment]
I wonder if it would be a good idea to have a page on the npm website with some of the info in this issue. There is a page in the getting started section for Linux users about installing npm modules globally here: https://docs.npmjs.com/getting-started/fixing-npm-permissions - although its not exactly the same as the issues in this issue, something similar for Windows might be a good idea.

edit: I just noticed the page now says:
> This section does not apply to Microsoft Windows. This chapter will be updated to address Windows in the near future.

so maybe it will be updated with info from here.

**Comment by TotallyInformation** [comment]
@franklinyu - I am not using it. Frankly, I didn't even know about it until someone mentioned it on a blog post. But that doesn't help other people who come across the issue does it. If Node wasn't ready for it, that's fine - after all, I'm _not_ paying for it. However, there needs to be clear information.

I do know lots of people at different levels of Microsoft as it happens. But I'm not sure what you are asking? As far as I can see - and maybe I just don't quite get the issue - there is nothing wrong with the default paths. There is simply an issue with the way that npx is configured when it is installed - presumably from the npm installation? Isn't that all that needs fixing?

@Darkle - Yes, that would be a very good idea.

**Comment by FranklinYu** [comment]
@TotallyInformation

> there is nothing wrong with the default paths.

There *is* something wrong with the default paths. I cannot figure out a reason why user path is *appended after* system path to form the effective path. In any case I would like the power to *override* the system path, and that power is available on Linux (not familiar with macOS but I believe it should be similar). It is very useful on Linux and I sometimes write my own "shim" script for some system commands, without administrator privilege. I would say that Windows is not designed with multi-user scenarios in mind.

The only thing NPX can do, is to *actively find and execute NPM in user path* (so bypassing Windows PATH searching mechanism), and more importantly, *make Node.js ship that improved version*. Otherwise the globally installed NPX will always be hidden by the one that came with Node.js. I believe NPM itself is already doing this for `npm.cmd`, because even if I explicitly specify the NPM from Node.js, it still uses the one from my home directory.

**Comment by TotallyInformation** [comment]
OK, I can see your issue with that. Windows does put system paths first. As I've always used Windows, I guess that is normal to me.

I suspect that the reason for this is security. If you put the user folders first - which are writable by the user of course - then malware could install something with the same name as a file in the system folders.

One of the benefits of using npm is that it adds the local bin folder to the start of the path so that you can run local executables. 

I certainly agree that this seems to be an issue that comes from the packaging with npm which itself is packaged with node.js. The actual issue has been fixed, but just needs to be known about until node.js is updated with the fix. I also agree that a test for this should be included in the node and npm packaging tests.

**Comment by schontz** [comment]
FYI I am running node 8.11.4, npm 6.4.0, and npx 10.2.0 on Windows 10. I was unable to run npx error free until I did what @magnusriga [did to fix the path issues](https://github.com/zkat/npx/issues/144#issuecomment-392474228). So it seems this is anything but closed.

**Comment by FranklinYu** [comment]
> I suspect that the reason for this is security. If you put the user folders first - which are writable by the user of course - then malware could install something with the same name as a file in the system folders.

@TotallyInformation That is false sense of security. If a user downloaded and run malware, and the antivirus did not stop it, he is *already* screwed. Nothing can help. Most (if not all) ways to prevent this can be bypassed by malware.

And that is not the design goal of this "system and user separation" (like preventing non-admin from modifying system path). The privilege system is designed to prevent malware from *one user* to harm *other users* on the same machine. If I share a Windows machine with my classmate, their malware won't affect me, as long as the administrator is doing the right thing.

**Comment by aboutqx** [comment]
2 years later still get this...

**Comment by FranklinYu** [comment]
@aboutqx Read the thread, buddy. It’s already been fixed. Use Node.js 10 if you are in doubt.

**Comment by aboutqx** [comment]
Ok，i update babel-core,and it works.

**Comment by uchikaprojects** [comment]
I am still having the same issue with npx

**Comment by FranklinYu** [comment]
@uchikaprojects Read the thread, buddy. It’s already been fixed. Use Node.js 10 if you are in doubt.

I should make this an auto-reply.

**Comment by uchikaprojects** [comment]
@franklinyu Thanks very much, let me check it out

**Comment by paulmelero** [comment]
**Upgrading to Node 10** fixed the issue. Remember to `npm ci`; as some of your system bindings might fail. 💪

**Comment by webworthydesign** [comment]
Just in case this helps someone. I had this error and it was being caused by a typo in Grunt. There is a section where we list the themes we want Grunt to rebuild in our project and one of them was spelled wrong. So it was a silly overlook that ended up being a big headache but in the end an easy fix.

A way to find it is to use the --verbose tag when running a grunt build. Hope that helps someone!

**Comment by sathyaprakash94** [comment]
I had the same issue, I resolved by refering the below documentation.
[https://reactjs.org/blog/2016/07/22/create-apps-with-no-configuration.html?utm_source=hashnode.com](url)

**Comment by praveens96** [comment]
> I had the same issue, I resolved by refering the below documentation.
> [https://reactjs.org/blog/2016/07/22/create-apps-with-no-configuration.html?utm_source=hashnode.com](url)

the link was broken.
