### ISSUE TITLE
Cache behavior

### ISSUE THREAD

**Issue by stuartpb** [zkat/npx#2]
I'm a little unclear on the proposed behavior around cached packages: if it already exists, is npx just going to link its existing binaries?

One of the things I'm thinking is that, considering the main use case I can see this being used for ("I found this npm package's command on Stack Overflow, let me try it"), npx should re-evaluate the latest version of the package available (against the semver) **every time it's run**, and update if a newer (non-prerelease) version is available (giving the same "against the latest version available" behavior it'd have if the package hadn't been retrieved yet).

Obviously that's a bit of network overhead that could introduce a lot of lag on every invocation, so maybe there should be global / user config and/or command-line options to elide the update check under certain circumstances. Some (but not all) of the dimensions I can see this being useful to slice on (not necessarily 1:1 with a desirable configuration surface):

- Available bandwidth / connectivity (for instance, I may want to only disable this check if I'm not connected to Wi-Fi, when I know it's not going to resolve)
- Which package is being checked against (I may have a script that runs `little-linter` individually against a hundred files, but `big-huge-framework-generator` only once per project, and I **never** want the technical debt that comes from being a single Big Huge Framework patch release behind)
- How recently the package was updated (and note that this can intersect the previous: I might want a package that gets multiple patches a day to check at every invocation, even invoked several times a minute, but a package that only gets updated annually I never want to check against)

**Comment by zkat** [comment]
npx is essentially equivalent to `npm i -g pkg && pkg <args>`, except with a custom global prefix. Since it's calling out to npm internally, that means you can use `.npmrc` as well as the `--userconfig <path>` option to provide custom settings to npm itself. For example, you can have `offline=true`, or `prefer-offline=true` to reduce network access.

Any fancier interactions should be done with npm itself. At that point, npx stops being an advantage. It's meant to be a tool to simplify things, not make things more complicated in a different way.

I'm not really sure about aiming for being performant enough to work as a fast automation tool, but we can talk more about that when the code is more complete and there's a better idea of the overall performance profile. There's plenty of ways to do this fast.
