### ISSUE TITLE
Feature request: npx script-name as an alias to npm run-script script-name

### ISSUE THREAD

**Issue by filipesilva** [zkat/npx#64]
One of the nice convenience features of `yarn` is the ability to run scripts directly via `yarn script-name`. 

This was the first thing I tried to do with `npx`. I kinda assumed it was there, but it seems it's not. Would it be possible to add? 

If added, `npm run build` or `npx build` would do the same thing, assuming there's a script named `build`.

I think that for the feature to be of use, it would have to be the default and not hidden behind a flag, otherwise one is better off doing `npm run script-name` anyway.

Let me know what you think. Cheers!

**Comment by zkat** [comment]
@filipesilva I'm inclined to not add this, and here's why:

A big thing I don't like about the `yarn` approach to these things that you mention is that it involves arbitrary fallback: if you have a `foo` script, you can never run `npx foo` and refer to the _binary_, if this feature were to exist. I think even if it were to be the opposite and binaries always shadowed scripts, this would still be a potentially confusing issue and, I think, overload the purpose of `npx`.

I think npx already helps with the _underlying_ issue of needing to do `npm run ...` a lot simply by virtue of the scoping that it does, as well as `npx -c`. I think it's better left to `npm` itself (or to third-party tools) to manage the execution of actual scripts.

The thing is, since I don't think a fallback is a good idea, the only way I'd add a feature like this to npx would be behind a flag of some sort (`npx --script bundle`), but that's already way more verbose than `npm run`, so I think `npm run` remains the best choice here.

Does that make sense?

**Comment by filipesilva** [comment]
It does make sense, and thank you for taking the time to explain your reasoning.

I agree that the arbitrary fallback / overloading is a very relevant concern, and don't really see a way around that. Using another tool to avoid having to write `npm run` also seems excessive, so keeping to `npm run` seems the best alternative.

**Comment by zkat** [comment]
Thanks for understanding! Keeping an eye out for good solutions to this is a good idea, fwiw. I'm gonna close this for now 'cause it sounds like we're on the same page about it now.

Thanks for taking the time to write out the request and convey your reasoning! Hope npx is otherwise serving you well.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10219633-315499911_2-s4-v1.png?transparent=1&palette=1&width=246)
